en:
  languageCode: en-us
  contentDir: content/en
  title: "Welcome to my site"
  description: "A personal website in English"
 
de:
  languageCode: de-de
  contentDir: content/de
  title: "Willkommen auf meiner Seite"
  description: "Eine persönliche Webseite auf Deutsch"
  menu:
    main:
      - name: "Über uns"
        url: "#about-us"
        weight: 1
